FROM node:12.16-alpine as BUILDER

WORKDIR /code

COPY package.json yarn.lock /code/

RUN yarn install

COPY . /code/

RUN yarn build

FROM nginx:alpine

COPY --from=BUILDER /code/dist /usr/share/nginx/html
